/* =========================================================
   CATÁLOGO — agregá o sacá canciones acá.
   { a: artista, t: título, yt:"ID_DE_YOUTUBE" }
   El ID es lo que va después de watch?v= en la URL del video.
   Si una canción no tiene yt, el juego la busca usando la clave de
   config.js (YouTube Data API v3). Con todos los IDs cargados, la
   clave deja de ser necesaria.
   ========================================================= */

const CANCIONES = [
  {a:"Soda Stereo", t:"De Música Ligera"},
  {a:"Soda Stereo", t:"Persiana Americana"},
  {a:"Soda Stereo", t:"Cuando Pase el Temblor"},
  {a:"Soda Stereo", t:"En la Ciudad de la Furia"},
  {a:"Charly García", t:"Demoliendo Hoteles"},
  {a:"Charly García", t:"Los Dinosaurios"},
  {a:"Charly García", t:"No Voy en Tren"},
  {a:"Charly García", t:"Rezo por Vos"},
  {a:"Sui Generis", t:"Canción para mi Muerte"},
  {a:"Serú Girán", t:"Seminare"},
  {a:"Fito Páez", t:"El Amor Después del Amor"},
  {a:"Fito Páez", t:"Mariposa Tecknicolor"},
  {a:"Fito Páez", t:"11 y 6"},
  {a:"Patricio Rey y sus Redonditos de Ricota", t:"Jijiji"},
  {a:"Patricio Rey y sus Redonditos de Ricota", t:"Un Poco de Amor Francés"},
  {a:"Los Fabulosos Cadillacs", t:"Matador"},
  {a:"Los Fabulosos Cadillacs", t:"Vasos Vacíos"},
  {a:"Los Fabulosos Cadillacs", t:"Mal Bicho"},
  {a:"Andrés Calamaro", t:"Flaca"},
  {a:"Andrés Calamaro", t:"Crímenes Perfectos"},
  {a:"Gustavo Cerati", t:"Crimen"},
  {a:"Gustavo Cerati", t:"Puente"},
  {a:"Babasónicos", t:"Irresponsables"},
  {a:"Babasónicos", t:"Los Calientes"},
  {a:"Almendra", t:"Muchacha (Ojos de Papel)"},
  {a:"Luis Alberto Spinetta", t:"Seguir Viviendo Sin Tu Amor"},
  {a:"Los Piojos", t:"Tan Solo"},
  {a:"Los Piojos", t:"El Farolito"},
  {a:"La Renga", t:"El Revelde"},
  {a:"Sumo", t:"La Rubia Tarada"},
  {a:"Sumo", t:"Mañana en el Abasto"},
  {a:"Virus", t:"Wadu Wadu"},
  {a:"Virus", t:"Imágenes Paganas"},
  {a:"Los Abuelos de la Nada", t:"Mil Horas"},
  {a:"Divididos", t:"¿Qué Ves?"},
  {a:"Divididos", t:"El 38"},
  {a:"Bersuit Vergarabat", t:"La Bolsa"},
  {a:"Los Auténticos Decadentes", t:"Loco (Tu Forma de Ser)"},
  {a:"Los Auténticos Decadentes", t:"La Guitarra"},
  {a:"Vicentico", t:"Los Caminos de la Vida"},
  {a:"Ratones Paranoicos", t:"Rock del Gato"},
  {a:"Attaque 77", t:"Hacelo por Mí"},
  {a:"Turf", t:"Loco un Poco"},
  {a:"Airbag", t:"Cae el Sol"},
  {a:"Tan Biónica", t:"Ciudad Mágica"},
  {a:"Miranda!", t:"Don"},
  {a:"Los Pericos", t:"El Ritual de la Banana"},
  {a:"Intoxicados", t:"Nunca Quise"},
  {a:"Kapanga", t:"El Mono Relojero"},
  {a:"Estelares", t:"Aire"},
  {a:"Catupecu Machu", t:"A Veces Vuelvo"},
  {a:"Las Pelotas", t:"Será"},
  {a:"Ciro y los Persas", t:"Antes y Después"},
  {a:"Conociendo Rusia", t:"Loco en el Desierto"},
  {a:"Los Twist", t:"Pensé que se Trataba de Cieguitos"},
  {a:"Los Gatos", t:"La Balsa"},
  {a:"Manal", t:"Jugo de Tomate"},
  {a:"Pappo's Blues", t:"El Tren de las 16"},
  {a:"Enanitos Verdes", t:"Lamento Boliviano"},
  {a:"Fabiana Cantilo", t:"Mi Enfermedad"},
  {a:"León Gieco", t:"Sólo le Pido a Dios"},
  {a:"Mercedes Sosa", t:"Alfonsina y el Mar"},
  {a:"Sandro", t:"Rosa Rosa"},
  {a:"Palito Ortega", t:"La Felicidad"},
  {a:"Piero", t:"Mi Viejo"},
  {a:"Gilda", t:"No Me Arrepiento de Este Amor"},
  {a:"Rodrigo", t:"La Mano de Dios"},
  {a:"Los Palmeras", t:"Olvídala"},
  {a:"Damas Gratis", t:"Se Te Ve la Tanga"},
  {a:"Bandana", t:"Guapas"},
  {a:"Soledad", t:"Tren del Cielo"},
  {a:"Abel Pintos", t:"Sin Principio ni Final"},
  {a:"Luciano Pereyra", t:"Que Suerte Tiene Él"},
  {a:"Los Nocheros", t:"Entre la Tierra y el Cielo"},
  {a:"Wos", t:"Canguro"},
  {a:"Duki", t:"Goteo"},
  {a:"Trueno", t:"Mamichula"},
  {a:"Nicki Nicole", t:"Colocao"},
  {a:"Tini", t:"Miénteme"},
  {a:"Emilia", t:"Jagger.mp3"},
  {a:"Milo J", t:"Rara Vez"},
  {a:"Dillom", t:"La Primera"},
  {a:"Ca7riel & Paco Amoroso", t:"Baby Gangsta"},
  {a:"Bizarrap", t:"Duki: Bzrp Music Sessions, Vol. 50"},
];
CANCIONES.forEach((c,i)=>{c.id=i; c.label=`${c.a} — ${c.t}`;});
